WebApp/Controllers/ConfigurationController.cs
using Microsoft.AspNetCore.Mvc;
using ConfigLib.Interfaces;
using DataAccess.Models;
using MongoDB.Bson;
using DataAccess.Interfaces;

namespace WebApp.Controllers
{
	public class ConfigurationController : Controller
	{
		private readonly IConfigurationRepository _configurationRepository;
		private readonly IConfigurationService _configurationService;
		private readonly IConfiguration _configuration;

		public ConfigurationController(IConfigurationRepository configurationRepository, IConfiguration configuration, IConfigurationService configurationService)
		{
			_configurationRepository = configurationRepository;
			_configuration = configuration;
			_configurationService = configurationService;
		}

		public async Task<IActionResult> Index()
		{
			var applicationName = _configuration["AppSettings:ApplicationName"];
			var configurations = await _configurationRepository.GetActiveConfigurationsAsync(applicationName);

			return View(configurations);
		}

		public async Task<IActionResult> Details(ObjectId id)
		{
			var configuration = await _configurationRepository.GetConfigurationAsync(id);

			if (configuration == null)
			{
				return NotFound();
			}

			return View(configuration);
		}

		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Create(ConfigurationRecord configurationRecord)
		{
			if (ModelState.IsValid)
			{
				await _configurationRepository.AddOrUpdateConfigurationAsync(configurationRecord);

				return RedirectToAction(nameof(Index));
			}

			return View(configurationRecord);
		}

		public async Task<IActionResult> Edit(ObjectId id)
		{
			var configuration = await _configurationRepository.GetConfigurationAsync(id);

			if (configuration == null)
			{
				return NotFound();
			}

			return View(configuration);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(ObjectId id, ConfigurationRecord configurationRecord)
		{
			if (id != configurationRecord.Id)
			{
				return BadRequest();
			}

			if (ModelState.IsValid)
			{
				await _configurationRepository.AddOrUpdateConfigurationAsync(configurationRecord);

				return RedirectToAction(nameof(Index));
			}

			return View(configurationRecord);
		}

		public async Task<IActionResult> Delete(ObjectId id)
		{
			var configuration = await _configurationRepository.GetConfigurationAsync(id);

			if (configuration == null)
			{
				return NotFound();
			}

			return View(configuration);
		}

		[HttpPost, ActionName("DeleteConfirmed")]
		public async Task<IActionResult> DeleteConfirmed(ObjectId id)
		{
			await _configurationRepository.DeleteConfigurationAsync(id);

			return RedirectToAction(nameof(Index));
		}
	}
}

WebApp/Views/Configuration/Create.cshtml
@model DataAccess.Models.ConfigurationRecord

@{
	ViewData["Title"] = "Konfigürasyon Ekle";
}

<h1>Konfigürasyon Ekle</h1>

<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Create">
			<div class="form-group">
				<label asp-for="Name" class="control-label"></label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Type" class="control-label"></label>
				<input asp-for="Type" class="form-control" />
				<span asp-validation-for="Type" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Value" class="control-label"></label>
				<input asp-for="Value" class="form-control" />
				<span asp-validation-for="Value" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ApplicationName" class="control-label"></label>
				<input asp-for="ApplicationName" class="form-control" />
				<span asp-validation-for="ApplicationName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<div class="form-check">
					@Html.LabelFor(model => model.IsActive, new { @class = "form-check-label" })
					@Html.CheckBoxFor(model => model.IsActive, new { @class = "form-check-input" })
				</div>
				<span asp-validation-for="IsActive" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Ekle" class="btn btn-primary" />
				<a asp-action="Index">
					<input style="width: 100px" value="Geri Dön" class="btn btn-warning" />
				</a>
			</div>
		</form>
	</div>
</div>

WebApp/Views/Configuration/Delete.cshtml
@model DataAccess.Models.ConfigurationRecord

@{
	ViewData["Title"] = "Konfigürasyonu Sil";
}

<h1>Konfigürasyonu Sil</h1>

<h4>Bu konfigürasyonu silmek istediğinize emin misiniz?</h4>
<div>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Id)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Id)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Name)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Name)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Type)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Type)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Value)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Value)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.IsActive)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.IsActive)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ApplicationName)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ApplicationName)
		</dd>
	</dl>
	<form asp-action="DeleteConfirmed">
		<input type="hidden" asp-for="Id" />
		<input type="submit" value="Sil" class="btn btn-danger" />
		<a asp-action="Index">
			<input style="width: 100px" value="Geri Dön" class="btn btn-warning" />
		</a>
	</form>
</div>

WebApp/Views/Configuration/Details.cshtml
@model DataAccess.Models.ConfigurationRecord

@{
	ViewData["Title"] = "Konfigürasyon Detayları";
}

<h1>Konfigürasyon Detayları</h1>
<hr />
<div>
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Id)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Id)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Name)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Name)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Type)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Type)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Value)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Value)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.IsActive)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.IsActive)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ApplicationName)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ApplicationName)
		</dd>
	</dl>
</div>
<div>
	<a asp-action="Edit" asp-route-id="@Model.Id">
		<input type="submit" value="Düzenle" class="btn btn-primary" />
	</a>
	<a asp-action="Index">
		<input style="width: 100px" value="Geri Dön" class="btn btn-warning" />
	</a>
</div>

WebApp/Views/Configuration/Edit.cshtml
@model DataAccess.Models.ConfigurationRecord

@{
	ViewData["Title"] = "Konfigürasyonu Düzenle";
}

<h1>Konfigürasyonu Düzenle</h1>

<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div class="form-group">
				<label asp-for="Name" class="control-label"></label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Type" class="control-label"></label>
				<input asp-for="Type" class="form-control" />
				<span asp-validation-for="Type" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Value" class="control-label"></label>
				<input asp-for="Value" class="form-control" />
				<span asp-validation-for="Value" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ApplicationName" class="control-label"></label>
				<input asp-for="ApplicationName" class="form-control" />
				<span asp-validation-for="ApplicationName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<div class="form-check">
					@Html.LabelFor(model => model.IsActive, new { @class = "form-check-label" })
					@Html.CheckBoxFor(model => model.IsActive, new { @class = "form-check-input" })
				</div>
				<span asp-validation-for="IsActive" class="text-danger"></span>
			</div>
			<br />
			<div class="form-group">
				<input type="submit" value="Kaydet" class="btn btn-primary" />
				<a asp-action="Index">
					<input type="submit" value="Geri Dön" class="btn btn-warning" />
				</a>
			</div>
		</form>
	</div>
</div>

WebApp/Views/Configuration/Index.cshtml
@model IEnumerable<DataAccess.Models.ConfigurationRecord>
@{
	ViewData["Title"] = "Konfigürasyon Kayıtları";
}

<h1>Konfigürasyon Kayıtları</h1>

<p class="btn-">
	<a asp-action="Create">
		<div class="form-group">
			<input type="submit" value="Ekle" class="btn btn-primary" />
		</div>
	</a>
</p>

<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.First().Id)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.First().Name)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.First().Type)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.First().Value)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.First().IsActive)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.First().ApplicationName)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Id)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Type)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Value)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.IsActive)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.ApplicationName)
				</td>
				<td>
					<a asp-action="Edit" asp-route-id="@item.Id">Düzenle</a> |
					<a asp-action="Details" asp-route-id="@item.Id">Detay</a> |
					<a asp-action="Delete" asp-route-id="@item.Id">Sil</a>
				</td>
			</tr>
		}
	</tbody>
</table>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - WebApp</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Configuration" asp-action="Index">SecilConfiguration</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Configuration" asp-action="Index">Ana Sayfa</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>
	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2024 - Melis Çoban Algül
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>